// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmMgewoVZ0vtO1b4NAyA1ZFwDYR9rxgTI',
    appId: '1:349249426296:web:d726682f9ec01463b06e8d',
    messagingSenderId: '349249426296',
    projectId: 'myloginapplication-e857c',
    authDomain: 'myloginapplication-e857c.firebaseapp.com',
    databaseURL: 'https://myloginapplication-e857c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapplication-e857c.appspot.com',
    measurementId: 'G-SPWDVBGQX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhEknLRlxqy1VDwHmCnGUESfAFLzbj4DY',
    appId: '1:349249426296:android:22f7ba71e21fc3a5b06e8d',
    messagingSenderId: '349249426296',
    projectId: 'myloginapplication-e857c',
    databaseURL: 'https://myloginapplication-e857c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapplication-e857c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6PMeJRo7Y_ylhOBW0OMcv_XwqCL4RkDM',
    appId: '1:349249426296:ios:9e10904f7e54616db06e8d',
    messagingSenderId: '349249426296',
    projectId: 'myloginapplication-e857c',
    databaseURL: 'https://myloginapplication-e857c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapplication-e857c.appspot.com',
    iosBundleId: 'com.example.myApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6PMeJRo7Y_ylhOBW0OMcv_XwqCL4RkDM',
    appId: '1:349249426296:ios:76f63b6889d7bb7fb06e8d',
    messagingSenderId: '349249426296',
    projectId: 'myloginapplication-e857c',
    databaseURL: 'https://myloginapplication-e857c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapplication-e857c.appspot.com',
    iosBundleId: 'com.example.myApp2.RunnerTests',
  );
}
